# Generated by Django 4.1.7 on 2023-04-29 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0007_mark2answer_mark2question_remove_user_rating_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mark2question',
            table='marks2questions',
        ),
    ]
