# Generated by Django 3.2.12 on 2023-06-12 06:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('askme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('photo', models.ImageField(blank=True, default='photos/default.jpg', null=True, upload_to='user_avatars/%Y/%m/%d', verbose_name='user_photo')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_staff', models.BooleanField(default=False, verbose_name='staff')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='registration_date')),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=3000, verbose_name='answer_text')),
                ('rating', models.IntegerField(default=0, verbose_name='rating')),
                ('status', models.CharField(choices=[('c', 'correct'), ('u', 'unknown')], default=('u', 'unknown'), max_length=1, verbose_name='answer_status')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_author', to=settings.AUTH_USER_MODEL, verbose_name='answer_author')),
            ],
            options={
                'db_table': 'answers',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='tag_name')),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='question_title')),
                ('text', models.CharField(max_length=3000, verbose_name='question_text')),
                ('rating', models.IntegerField(default=0, verbose_name='rating')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_of_question', to=settings.AUTH_USER_MODEL, verbose_name='question_author')),
                ('tag', models.ManyToManyField(related_name='questions', to='askme.Tag', verbose_name='question_tag')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Mark2Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('l', 'like'), ('d', 'dislike')], max_length=1, verbose_name='mark_type')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark2question', to=settings.AUTH_USER_MODEL)),
                ('to_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark', to='askme.question')),
            ],
            options={
                'db_table': 'marks2questions',
            },
        ),
        migrations.CreateModel(
            name='Mark2Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('l', 'like'), ('d', 'dislike')], max_length=1, verbose_name='mark_type')),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark2answer', to=settings.AUTH_USER_MODEL)),
                ('to_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark', to='askme.answer')),
            ],
            options={
                'db_table': 'marks2answers',
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='to_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_to_question', to='askme.question', verbose_name='answer2question'),
        ),
    ]
