# Generated by Django 3.2.12 on 2023-06-12 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_author', to='askme.user', verbose_name='answer_author'),
        ),
        migrations.AlterField(
            model_name='mark2answer',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark2answer', to='askme.user'),
        ),
        migrations.AlterField(
            model_name='mark2question',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark2question', to='askme.user'),
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_of_question', to='askme.user', verbose_name='question_author'),
        ),
    ]
