# Generated by Django 4.1.7 on 2023-04-12 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='user_photos', verbose_name='Фото пользователя'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tag',
            field=models.ManyToManyField(null=True, related_name='questions', to='askme.tag', verbose_name='Теги'),
        ),
    ]
