# Generated by Django 4.1.7 on 2023-04-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0003_rename_answers_answer_alter_question_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='status',
            field=models.CharField(choices=[('r', 'right'), ('w', 'wrong'), ('u', 'unknown')], max_length=1, verbose_name='Статус'),
        ),
    ]
