# Generated by Django 4.1.7 on 2023-04-12 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0004_alter_answer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='status',
            field=models.CharField(choices=[('r', 'right'), ('w', 'wrong')], max_length=1, null=True, verbose_name='Статус'),
        ),
    ]
