# Generated by Django 4.1.7 on 2023-04-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0005_alter_answer_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='status',
            field=models.CharField(choices=[('r', 'right'), ('u', 'unknown')], default=('u', 'unknown'), max_length=1, verbose_name='Статус'),
        ),
    ]
