# Generated by Django 4.1.7 on 2023-04-16 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0008_user_date_joined_user_is_active_user_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='answer',
            table='Answers',
        ),
        migrations.AlterModelTable(
            name='mark',
            table='Marks',
        ),
        migrations.AlterModelTable(
            name='question',
            table='Questions',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='Tags',
        ),
        migrations.AlterModelTable(
            name='user',
            table='Users',
        ),
    ]
