# Generated by Django 4.1.7 on 2023-04-16 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0009_alter_answer_table_alter_mark_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Имя'),
        ),
    ]
