# Generated by Django 4.1.7 on 2023-04-16 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0010_alter_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mark',
            old_name='status',
            new_name='name',
        ),
    ]
