# Generated by Django 4.1.7 on 2023-04-17 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_author', to='askme.user', verbose_name='answer_author'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='status',
            field=models.CharField(choices=[('r', 'right'), ('u', 'unknown')], default=('u', 'unknown'), max_length=1, verbose_name='answer_status'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=3000, verbose_name='answer_text'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='to_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_to_question', to='askme.question', verbose_name='answer2question'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks_given', to='askme.user', verbose_name='sandler'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='name',
            field=models.CharField(choices=[('l', 'like'), ('d', 'dislike')], max_length=1, verbose_name='mark_type'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='to_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks_received', to='askme.user', verbose_name='recipient'),
        ),
        migrations.AlterField(
            model_name='question',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_of_question', to='askme.user', verbose_name='question_author'),
        ),
        migrations.AlterField(
            model_name='question',
            name='tag',
            field=models.ManyToManyField(related_name='questions', to='askme.tag', verbose_name='question_tag'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=3000, verbose_name='question_text'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=255, verbose_name='question_title'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, verbose_name='tag_name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True, verbose_name='registration_date'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='staff'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='user_name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='./static/img/user_avatars', verbose_name='user_photo'),
        ),
        migrations.AlterField(
            model_name='user',
            name='rating',
            field=models.IntegerField(verbose_name='rating'),
        ),
        migrations.AlterModelTable(
            name='answer',
            table='answers',
        ),
        migrations.AlterModelTable(
            name='mark',
            table='marks',
        ),
        migrations.AlterModelTable(
            name='question',
            table='questions',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='tags',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
