# Generated by Django 4.1.7 on 2023-04-22 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0004_alter_user_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='./static/img/photos/default.jpg', null=True, upload_to='./static/img/user_avatars', verbose_name='user_photo'),
        ),
    ]
