# Generated by Django 4.1.7 on 2023-04-29 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0006_alter_user_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark2Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('l', 'like'), ('d', 'dislike')], max_length=1, verbose_name='mark_type')),
            ],
            options={
                'db_table': 'marks2answers',
            },
        ),
        migrations.CreateModel(
            name='Mark2Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('l', 'like'), ('d', 'dislike')], max_length=1, verbose_name='mark_type')),
            ],
            options={
                'db_table': 'marks2question',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='rating',
        ),
        migrations.AddField(
            model_name='answer',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='rating'),
        ),
        migrations.AddField(
            model_name='question',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='rating'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='status',
            field=models.CharField(choices=[('c', 'correct'), ('u', 'unknown')], default=('u', 'unknown'), max_length=1, verbose_name='answer_status'),
        ),
        migrations.DeleteModel(
            name='Mark',
        ),
        migrations.AddField(
            model_name='mark2question',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark2question', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mark2question',
            name='to_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark', to='askme.question'),
        ),
        migrations.AddField(
            model_name='mark2answer',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark2answer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mark2answer',
            name='to_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark', to='askme.answer'),
        ),
    ]
