# Generated by Django 4.1.7 on 2023-04-29 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0008_alter_mark2question_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark2answer',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark2answer', to='askme.user'),
        ),
        migrations.AlterField(
            model_name='mark2question',
            name='from_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mark2question', to='askme.user'),
        ),
    ]
