# Generated by Django 4.1.7 on 2023-05-21 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0009_alter_mark2answer_from_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='./static/img/photos/default.jpg', null=True, upload_to='./media/user_avatars/%Y/%m/%d/', verbose_name='user_photo'),
        ),
    ]
