# Generated by Django 4.1.7 on 2023-05-21 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0016_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='./static/img/photos/default.jpg', null=True, upload_to='./static/img/user_avatars', verbose_name='user_photo'),
        ),
    ]
