# Generated by Django 4.1.7 on 2023-05-21 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0019_alter_user_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, default='photos/default.jpg', null=True, upload_to='user_avatars/%Y/%m/%d', verbose_name='user_photo'),
        ),
    ]
